name: "Prepare release"

on:
  push:
    tags:
      - "release-*"
  workflow_dispatch:
    # allows manual trigger

permissions:
  contents: "write"

env:
  THIRD_PARTY_BASE_DIR: "third-party"
jobs:
  build-macos:
    name: Build on macOS
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: CMake configure
        run: cmake . -Bbuild -DCMAKE_BUILD_TYPE=Release
      - name: Build
        #run: make -Cbuild -j$(sysctl -n hw.ncpu) steam_api
 run: |
      SDKROOT=$(xcrun --sdk macosx --show-sdk-path) cmake . -Bbuild -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_DEPLOYMENT_TARGET=10.12 -DCMAKE_OSX_SYSROOT=macosx10.12
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          files: |
            build/libsteam_api.dylib
            build/lobby_connect
            build/generate_interfaces_file
