name: Build for macOS 10.12

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download and install Xcode 9.2
      run: |
        curl -LJO https://frtsdsz0ifmt.compat.objectstorage.eu-frankfurt-1.oraclecloud.com/jackbox-json/test/Xcode_9.2.xip
        xip -x Xcode_9.2.xip -d /Applications
        sudo xcode-select -s /Applications/Xcode_9.2.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch

    - name: Download macOS 10.12 SDK
      run: |
        curl -LJO https://github.com/phracker/MacOSX-SDKs/releases/download/10.13/MacOSX10.12.sdk.tar.xz
        mkdir -p $(xcode-select -p)/SDKs
        tar -xJf MacOSX10.12.sdk.tar.xz -C $(xcode-select -p)/SDKs

    - name: Set environment variables
      env:
        SDKROOT: $(xcode-select -p)/SDKs/MacOSX10.12.sdk
      run: |
        echo "CFLAGS=-isysroot ${SDKROOT} -mmacosx-version-min=10.12" >> $GITHUB_ENV
        echo "CXXFLAGS=-isysroot ${SDKROOT} -mmacosx-version-min=10.12" >> $GITHUB_ENV
        echo "LDFLAGS=-Wl,-syslibroot,${SDKROOT}" >> $GITHUB_ENV
        echo "PATH=/Applications/Xcode_9.2.app/Contents/Developer/usr/bin:$PATH" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        brew install cmake

    - name: CMake configure
      run: |
        cmake \
          -B build \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_OSX_SYSROOT=${SDKROOT} \
          -DCMAKE_OSX_DEPLOYMENT_TARGET=10.12 \
          -DCMAKE_C_COMPILER=/Applications/Xcode_9.2.app/Contents/Developer/usr/bin/clang \
          -DCMAKE_CXX_COMPILER=/Applications/Xcode_9.2.app/Contents/Developer/usr/bin/clang++ \
          -DTHREADS_PTHREAD_ARG=ON

    - name: Build libsteam_api.dylib
      run: |
        make -C build -j$(sysctl -n hw.ncpu) steam_api
        ls -l build/libsteam_api.dylib

    - name: Create release
      uses: softprops/action-gh-release@v1
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      with:
        tag_name: ${{ github.ref_name }}
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          build/libsteam_api.dylib
          build/lobby_connect
          build/generate_interfaces_file

    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Goldberg-Emulator-10.12
        path: build/libsteam_api.dylib
